config/routes.rb
Microdiario::Application.routes.draw do
  root to: 'client#show'

  match '/search/:term' => 'posts#search'
  resources :posts

  namespace :backend do
    root to: 'posts#index'
    resources :posts
    resources :users
  end

  match "/auth/:provider/callback" => "sessions#create"
  match "/logout" => "sessions#destroy", :as => :logout
  match "/entrar" => "sessions#new", :as => :login
  match "/enter/:id" => "sessions#enter" if Rails.env.development?
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Search

  field :body, :type => String
  field :date_at, :modeltype => String
  field :location, :type => String

  referenced_in :user
#  references_many :tags

  default_scope :order_by => [:date_at, :desc]
  search_in :body#, :tags => :name
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  field :name

  referenced_in :post
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider, :type => String
  field :uid, :type => String
  field :name, :type => String
  field :email, :type => String
  field :admin, :type => Boolean
  references_many :posts

  def admin?

  end


  def self.create_with_omniauth(auth)
    begin
      create! do |user|
        user.provider = auth['provider']
        user.uid = auth['uid']
        if auth['user_info']
          user.name = auth['user_info']['name'] if auth['user_info']['name'] # Twitter, Google, Yahoo, GitHub
          user.email = auth['user_info']['email'] if auth['user_info']['email'] # Google, Yahoo, GitHub
        end
        if auth['extra']['user_hash']
          user.name = auth['extra']['user_hash']['name'] if auth['extra']['user_hash']['name'] # Facebook
          user.email = auth['extra']['user_hash']['email'] if auth['extra']['user_hash']['email'] # Facebook
        end
      end
    rescue Exception
      raise Exception, "cannot create user record"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def require_user
      if !current_user
        redirect_to login_path, :alert => 'Debes identificarte.'
      end
    end

end

app/controllers/backend/application_controller.rb
# encoding: utf-8

class Backend::ApplicationController < ApplicationController
  protect_from_forgery
  before_filter :require_admin

  protected
  def require_admin
    unless current_user || current_user.admin?
      flash[:error] = 'Sólo para administradorxs...'
      redirect_to root_path
    end
  end

end

app/controllers/backend/posts_controller.rb
class Backend::PostsController < Backend::ResourceController
end

app/controllers/backend/resource_controller.rb
class Backend::ResourceController < Backend::ApplicationController
  layout 'backend'
  inherit_resources
  #has_scope :page, default: 1
  respond_to :html
end

app/controllers/backend/users_controller.rb
class Backend::UsersController < Backend::ResourceController
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  before_filter :require_user

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_user
  respond_to :html, :json

  def index
    @posts = Post.all
    respond_with @posts
  end

  def search
    @term = params[:term]
    @posts = Post.search @term
  end

  def create
    @post = Post.new(params[:post])
    @post.user = current_user
    @post.save
    respond_with @post, location: posts_path
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    respond_with @post, location: posts_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Bienvenidx #{user.name}"
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => 'Signed out!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(title)
    content_for(:title) { title }
    content_tag :h1, title
  end
end

app/helpers/backend/application_helper.rb
module Backend::ApplicationHelper
end

app/helpers/backend/resource_helper.rb
module Backend::ResourceHelper

  def attributes
    resource_class.fields.keys  - %w(_id created_at updated_at)
  end

end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/backend/resource/_form.html.erb
<%= simple_form_for [:backend, resource],
  html: {class: 'form-stacked'} do |form| %>
<% attributes.each do |attribute| %>
<%= form.input attribute %>
<% end %>
<div class="actions">
<%= form.submit 'Guardar', class: 'btn' %>
</div>

<% end %>

app/views/backend/resource/_index.html.erb
<%= title "#{resource_class.name} list" %>

<%= link_to 'New', new_resource_path(resource_class), class: 'btn' %>

<div class="pagination">
  <%#= paginate collection %>
</div>

<table class="common-table zebra-striped">
  <thead>
    <tr>
      <% attributes.each do |attribute| %>
        <th><%= resource_class.human_attribute_name(attribute) %></th>
      <% end %>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |resource| %>
      <tr>
      <% attributes.each do |attribute| %>
        <td><%= resource.public_send(attribute).to_s.truncate(20) %></td>
      <% end %>
      <td>
        <%= link_to 'show', resource_path(resource) %>
        <%= link_to 'edit', edit_resource_path(resource) %>
        <%=  link_to 'destroy', resource_path(resource), method: :delete, confirm: "Are you sure?" %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/backend/resource/_show.html.erb
<%= link_to raw('&larr; Back to list'), [:backend, resource_class] %>
<%= title resource_class.name %>

<h2>Attributes</h2>
<dl>
<% attributes.each do |attribute| %>
<dt><%= resource_class.human_attribute_name(attribute) %></dt>
<dd><%= resource.public_send(attribute).to_s %></dd>
<% end %>
</dl>
<div class="actions">
<%= link_to 'Edit', edit_resource_path(resource), class: 'btn' %>
</div>

app/views/backend/resource/edit.html.erb
<%= title "Edit #{resource_class.name}" %>

<%= render 'form', attributes: attributes %>

app/views/backend/resource/index.html.erb
<%= render 'index', attributes: attributes %>

app/views/backend/resource/new.html.erb
<%= title "New #{resource_class.name}" %>

<%= render 'form', attributes: attributes %>

app/views/backend/resource/show.html.erb
<%= render 'show', attributes: attributes %>

app/views/client/show.html.erb
<div id="alerts"></div>
<div id="newPost"></div>
<div id="posts"></div>

<script type="text/javascript">
  $(function() {
    // Blog is the app name
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microdiario</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="topbar">
  <div class="fill">
    <div class="container">
      <h3><a href="/">Microdiario</a></h3>

      <% if current_user %>
      <form id="search" action="#">
        <input type="text" name="term" id="term" placeholder="Buscar ...">
      </form>
      <ul class="nav secondary-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle"><%= current_user.name %></a>
              <ul class="dropdown-menu">
                <li><a href="#">Salir</a></li>
                <li><a href="#">Perfil</a></li>
                <li class="divider"></li>
                <li><a href="#">Ayuda</a></li>
              </ul>
            </li>
      </ul>
      <% end %>
    </div>
  </div>
</div>

<div id="viewport">
  <div id="page" class="container">
    <div id="flashes">
      <% flash.each do |name, msg| %>
          <% clazz = name == :notice ? 'success' : name %>
          <% clazz = 'error' if name == :alert %>
          <%= content_tag :div, :class => "flash alert-message #{clazz}" do %>
              <a class="close" href="#">×</a>
              <%= content_tag :p, msg %>
          <% end %>
      <% end %>
    </div>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaker backend - <%= yield :title %></title>
  <%= javascript_include_tag "backend" %>
  <%= stylesheet_link_tag "backend" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="topbar">
      <div class="fill">
        <div class="container">
          <h3><%= link_to 'Microdiario backend', backend_root_path %></h3>
          <ul>
            <li><%= link_to 'Posts', backend_posts_path %></li>
            <li><%= link_to 'Users', backend_users_path %></li>
            <li><%= link_to 'Microdiario', root_path %>
          </ul>
        </div>
      </div> <!-- /fill -->
<ul class="nav secondary-menu">
  <li><%#= current_user.name %></li>
</ul>

    </div>
<div class="container">
<div class="page">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/posts/_post.html.erb
<div class="post" id="post-<%= post.id %>">
<%= post.body %>
<%= post.created_at %>
<div class="actups">
<%= link_to 'Borrar', post, method: :delete, confirm: 'Seguro?' %>
</div>

app/views/posts/index.html.erb
<%= @posts.to_json %>

app/views/posts/search.html.erb
<%= title "Buscar '#{@term}'" %>

<%= render @posts %>